title: Worst Case Scenario Projects
description: This page is being built to highlight projects in my crazy data science journey! 
show_downloads: true
google_analytics: true
theme: jekyll-theme-midnight
